export type CliDomain =
  | "chat"
  | "reports"
  | "recipes"
  | "agents"
  | "projects"
  | "connections"
  | "credentials"
  | "billing"
  | "frontend"
  | "config"
  | "diagnostics"
  | "sessions"
  | "models"
  | "setup"
  | "mcp";

export interface CliCommandMetadata {
  name: string;
  description: string;
  options: string[];
  domain: CliDomain;
  workflows?: string[];
}

const authOptions = [
  "--base-url",
  "--access-key",
  "--access-key-stdin",
  "--non-interactive",
];

const outputOptions = [
  "--format",
  "--output",
  "--open",
  "--print-url",
  "--no-open",
  "--frontend-url",
];

export const cliCommands: CliCommandMetadata[] = [
  {
    name: "tui",
    description: "Open the CloudEval Terminal UI",
    domain: "chat",
    options: [
      "--base-url",
      "--tab",
      "--project",
      "--frontend-url",
      "--mode",
      "--access-key",
      "--access-key-stdin",
      "--model",
      "--debug",
      "--health-check",
      "--no-banner",
      "--animate",
      "--no-anim",
      "--verbose",
      "--profile",
      "--help",
    ],
    workflows: ["tui"],
  },
  {
    name: "chat",
    description: "Start an interactive chat session",
    domain: "chat",
    options: [
      "--base-url",
      "--access-key",
      "--access-key-stdin",
      "--conversation",
      "--continue",
      "--resume",
      "--model",
      "--mode",
      "--debug",
      "--health-check",
      "--no-banner",
      "--animate",
      "--no-anim",
      "--verbose",
      "--profile",
      "--help",
    ],
    workflows: ["chat", "sessions resume"],
  },
  {
    name: "ask",
    description: "Ask a single question",
    domain: "chat",
    options: [
      ...authOptions,
      "--project",
      "--model",
      "--thread",
      "--output",
      "--format",
      "--json",
      "--progress",
      "--quiet",
      "--no-color",
      "--open",
      "--print-url",
      "--no-open",
      "--frontend-url",
      "--debug",
      "--verbose",
      "--profile",
      "--help",
    ],
    workflows: ["ask"],
  },
  {
    name: "agent",
    description: "Run a non-interactive agent-mode task",
    domain: "chat",
    options: [
      ...authOptions,
      "--project",
      "--model",
      "--thread",
      "--output",
      "--format",
      "--json",
      "--progress",
      "--quiet",
      "--no-color",
      "--open",
      "--print-url",
      "--no-open",
      "--frontend-url",
      "--debug",
      "--verbose",
      "--profile",
      "--help",
    ],
    workflows: ["agent"],
  },
  {
    name: "agents",
    description: "List, inspect, and run CloudEval Agent Profiles",
    domain: "agents",
    options: [
      "list",
      "show",
      "run",
      ...authOptions,
      "--project",
      "--model",
      "--thread",
      "--format",
      "--output",
      "--progress",
      "--frontend-url",
      "--print-url",
      "--no-hooks",
      "--profile",
      "--help",
    ],
    workflows: ["agents list", "agents show", "agents run"],
  },
  {
    name: "reports",
    description: "Access cost and Well-Architected Framework reports",
    domain: "reports",
    options: [
      "list",
      "show",
      "cost",
      "waf",
      "download",
      "run",
      "rules",
      ...authOptions,
      "--project",
      "--format",
      "--raw",
      "--parsed",
      "--formatted",
      "--kind",
      "--period",
      "--view",
      "--report",
      "--severity",
      "--type",
      "--timestamp",
      "--region",
      "--currency",
      "--no-time-series",
      "--no-save-report",
      "--wait",
      "--poll-interval",
      "--output",
      "--open",
      "--print-url",
      "--no-open",
      "--frontend-url",
      "--profile",
      "--help",
    ],
    workflows: [
      "reports list",
      "reports show",
      "reports cost",
      "reports waf",
      "reports download",
      "reports run",
      "reports rules",
    ],
  },
  {
    name: "recipes",
    description: "CloudEval reusable recipes and agent skills",
    domain: "recipes",
    options: [
      "list",
      "show",
      "run",
      "--project",
      "--connection-id",
      "--credential-id",
      "--range",
      "--template-file",
      "--template-url",
      "--parameters-file",
      "--parameters-url",
      "--provider",
      "--name",
      "--output-path",
      "--output-dir",
      "--client",
      "--layout",
      "--model",
      "--thread",
      "--format",
      "--output",
      "--progress",
      "--quiet",
      "--frontend-url",
      ...authOptions,
      "--profile",
      "--help",
    ],
    workflows: ["recipes list", "recipes show", "recipes run"],
  },
  {
    name: "projects",
    description: "Project utilities",
    domain: "projects",
    options: [
      "list",
      "get",
      "open",
      "create",
      "export-diagram",
      "--template-url",
      "--template-file",
      "--parameters-file",
      "--parameters-url",
      "--name",
      "--description",
      "--provider",
      "--layout",
      "--labels",
      "--headers-output",
      "--public",
      "--sync-version",
      "--json",
      ...outputOptions,
      ...authOptions,
      "--profile",
      "--help",
    ],
    workflows: [
      "projects list",
      "projects get",
      "projects open",
      "projects create",
      "projects export-diagram",
    ],
  },
  {
    name: "credentials",
    description: "Manage CloudEval access-key credentials",
    domain: "credentials",
    options: [
      "templates",
      "create",
      "list",
      "inspect",
      "revoke",
      "--template",
      "--name",
      "--project",
      "--expires",
      "--capabilities",
      "--reason",
      "--idempotency-key",
      "--format",
      "--output",
      ...authOptions,
      "--profile",
      "--help",
    ],
    workflows: [
      "credentials templates",
      "credentials create",
      "credentials list",
      "credentials inspect",
      "credentials revoke",
    ],
  },
  {
    name: "connections",
    description: "Connection utilities",
    domain: "connections",
    options: [
      "list",
      "get",
      "open",
      ...outputOptions,
      ...authOptions,
      "--profile",
      "--help",
    ],
    workflows: ["connections list", "connections get", "connections open"],
  },
  {
    name: "billing",
    description: "Billing and usage utilities",
    domain: "billing",
    options: [
      "summary",
      "plans",
      "usage",
      "ledger",
      "invoices",
      "topups",
      "topup",
      "buy",
      "notifications",
      "--currency",
      "--country-code",
      "--contact-email",
      "--contact-phone",
      "--contact-country-code",
      "--return-to",
      "--range",
      "--start-at",
      "--end-at",
      "--granularity",
      "--action-type",
      "--model",
      "--outcome",
      "--charge-status",
      "--limit",
      "--cursor",
      ...outputOptions,
      ...authOptions,
      "--profile",
      "--help",
    ],
    workflows: [
      "billing summary",
      "billing usage",
      "billing ledger",
      "billing invoices",
      "billing topups",
      "billing topups buy",
      "billing topup",
      "billing plans",
      "billing notifications",
    ],
  },
  {
    name: "credits",
    description: "Show current credit stats",
    domain: "billing",
    options: [...outputOptions, ...authOptions, "--profile", "--help"],
    workflows: ["credits"],
  },
  {
    name: "open",
    description: "Open CloudEval frontend deeplinks",
    domain: "frontend",
    options: [
      "overview",
      "chat",
      "projects",
      "project",
      "connections",
      "connection",
      "reports",
      "billing",
      "--base-url",
      "--frontend-url",
      "--print-url",
      "--no-open",
      "--thread",
      "--project",
      "--tab",
      "--view",
      "--layout",
      "--node",
      "--resource",
      "--file",
      "--files",
      "--cursor",
      "--selection",
      "--workspace-focus",
      "--presentation",
      "--download-pdf",
      "--pdf-verbosity",
      "--download-report",
      "--report-verbosity",
      "--profile",
      "--help",
    ],
    workflows: [
      "open overview",
      "open chat",
      "open projects",
      "open project",
      "open connections",
      "open connection",
      "open reports",
      "open billing",
    ],
  },
  {
    name: "capabilities",
    description: "Show machine-readable CloudEval CLI capabilities",
    domain: "diagnostics",
    options: ["--format", "--live", ...authOptions, "--profile", "--help"],
    workflows: ["capabilities"],
  },
  {
    name: "identity",
    description: "Show the current CloudEval identity",
    domain: "config",
    options: ["--format", "--output", ...authOptions, "--profile", "--help"],
    workflows: ["identity"],
  },
  {
    name: "mcp",
    description: "Model Context Protocol utilities",
    domain: "mcp",
    options: [
      "status",
      "setup",
      "serve",
      "--base-url",
      "--frontend-url",
      "--access-key",
      "--toolset",
      "--dry-run",
      "--command",
      "--config-path",
      "--format",
      "--output",
      "--verbose",
      "--profile",
      "--help",
    ],
    workflows: ["mcp status", "mcp setup", "mcp serve"],
  },
  {
    name: "login",
    description: "Authenticate with CloudEval",
    domain: "config",
    options: ["--base-url", "--headless", "--verbose", "--profile", "--show-sensitive-ids", "--help"],
    workflows: ["login"],
  },
  {
    name: "logout",
    description: "Log out and clear stored authentication state",
    domain: "config",
    options: ["--base-url", "--all-devices", "--profile", "--help"],
    workflows: ["logout"],
  },
  {
    name: "auth",
    description: "Authentication utilities",
    domain: "config",
    options: ["status", "--base-url", "--format", "--profile", "--show-sensitive-ids", "--verbose", "--help"],
    workflows: ["auth status"],
  },
  {
    name: "update",
    description: "Update CloudEval CLI to the latest published version",
    domain: "setup",
    options: [
      "--check",
      "-c",
      "--yes",
      "-y",
      "--format",
      "-f",
      "--output",
      "-o",
      "--profile",
      "--help",
    ],
    workflows: ["update"],
  },
  {
    name: "banner",
    description: "Preview the startup banner and terminal capabilities",
    domain: "diagnostics",
    options: ["--profile", "--help"],
    workflows: ["banner"],
  },
  {
    name: "completion",
    description: "Print shell completion script",
    domain: "diagnostics",
    options: [
      "bash",
      "zsh",
      "fish",
      "powershell",
      "install",
      "uninstall",
      "--shell",
      "--bin",
      "--profile",
      "--help",
    ],
    workflows: ["completion"],
  },
  {
    name: "help",
    description: "Display help for humans or agents",
    domain: "diagnostics",
    options: ["agents", "--profile", "--help"],
    workflows: ["help", "help agents"],
  },
  {
    name: "config",
    description: "View and edit local CloudEval CLI settings",
    domain: "config",
    options: [
      "show",
      "get",
      "set",
      "unset",
      "path",
      "profiles",
      "--profile",
      "--format",
      "--output",
      "--help",
    ],
    workflows: [
      "config show",
      "config get",
      "config set",
      "config unset",
      "config path",
      "config profiles",
    ],
  },
  {
    name: "setup",
    description: "Configure CloudEval CLI defaults",
    domain: "setup",
    options: [
      "--non-interactive",
      "--base-url",
      "--frontend-url",
      "--project",
      "--model",
      "--mode",
      "--profile",
      "--format",
      "--output",
      "--help",
    ],
    workflows: ["setup"],
  },
  {
    name: "doctor",
    description: "Diagnose local CLI configuration and environment",
    domain: "diagnostics",
    options: ["--base-url", "--format", "--deep", "--profile", "--show-sensitive-ids", "--verbose", "--help"],
    workflows: ["doctor"],
  },
  {
    name: "status",
    description: "Show CloudEval CLI status",
    domain: "diagnostics",
    options: ["--base-url", "--format", "--profile", "--show-sensitive-ids", "--verbose", "--help"],
    workflows: ["status"],
  },
  {
    name: "models",
    description: "List models and manage the default model",
    domain: "models",
    options: [
      "list",
      "default",
      "get",
      "set",
      ...authOptions,
      "--format",
      "--output",
      "--profile",
      "--help",
    ],
    workflows: ["models list", "models default get", "models default set"],
  },
  {
    name: "sessions",
    description: "Manage local CLI session history",
    domain: "sessions",
    options: [
      "list",
      "get",
      "search",
      "rename",
      "export",
      "delete",
      "prune",
      "--limit",
      "--output",
      "--format",
      "--yes",
      "--profile",
      "--help",
    ],
    workflows: [
      "sessions list",
      "sessions get",
      "sessions search",
      "sessions rename",
      "sessions export",
      "sessions delete",
      "sessions prune",
    ],
  },
];

export const commandNames = cliCommands.map((command) => command.name);

export const buildDomains = (): Record<CliDomain, string[]> => {
  const domains = {} as Record<CliDomain, string[]>;
  for (const command of cliCommands) {
    domains[command.domain] = [
      ...(domains[command.domain] ?? []),
      ...(command.workflows ?? [command.name]),
    ];
  }
  return domains;
};
